### ISSUE TITLE
Proper XML parsing

### ISSUE THREAD

**Issue by vinipsmaker** [sbstp/rust-igd#7]
Hi, is there interest in [properly parsing the XML documents received through the wire](https://github.com/SBSTP/rust-igd/blob/0d98c6c5fc1c01ada82ccaa69c395c0eb98bdd1b/src/external.rs#L54) or is it too much overkill?

**Comment by SBSTP** [comment]
I would like to truly and fully support the protocol. However the state of Rust & XML isn't too good at the moment. There's a good xml tokenizer library, but no DOM library (it's basically impossible to fully implement on stable, because the DOM allows multiple owners & mutable pointers, and Weak pointers are unstable). Also there's no soap library, because it needs a DOM, obviously.

I'm not working on this full time, obviously, but I'd like it to grow and become the reference for IGD in rust. I started working on a partial DOM implementation, and then I'll work on a SOAP library.

**Comment by vinipsmaker** [comment]
> but I'd like it to grow and become the reference for IGD in rust

Interesting. Looks promising.
:)

I may do a PR for issue #1 soon.

**Comment by canndrew** [comment]
This can be closed now.
